font_family      monospace
font_size        11.0

background       #0d0d0d
foreground       #c5c5c5
cursor           #c5c5c5

color0  #1c1c1c
color8  #3c3c3c
color1  #c94f4f
color9  #d97a7a
color2  #8ca85e
color10 #a9c47e
color3  #c9a94f
color11 #d9c57a
color4  #5e8ca8
color12 #7ea9c4
color5  #a85ea8
color13 #c47ec4
color6  #5ea8a8
color14 #7ec4c4
color7  #c5c5c5
color15 #e5e5e5

window_padding_width 0
hide_window_decorations yes
confirm_os_window_close 0
